# Bildung in Deutschland 2006 bis 2026: Vorverarbeitung des Textkorpus

## Worum es geht

Der nationale Bildungsbericht "Bildung in Deutschland" erscheint seit 2006 alle zwei Jahre, 2026 zum elften Mal. Er beschreibt das Bildungswesen indikatorengestützt von der frühen Bildung bis zur Weiterbildung und enthält in jeder Ausgabe ein wechselndes Schwerpunktkapitel. Nach 20 Jahren Berichterstattung liegt damit ein Textkorpus vor, das bisher nicht systematisch ausgewertet wurde.

Dieses Projekt analysiert die elf Berichte als Textdaten mit Methoden der Computational Social Science. Im Mittelpunkt stehen Inhalte, nicht Formulierungen oder Stil. Stil und Schreibweise ändern sich über 20 Jahre mit wechselnden Autorengruppen, das ist erwartbar und nicht Gegenstand der Analyse.

## Forschungsfragen

1. Welche Themen bleiben über 20 Jahre konstant, welche kommen hinzu, welche gehen zurück?
2. Welche Herausforderungen benennt der Bericht wiederholt, und wie entwickeln sich die zugehörigen Indikatoren im selben Zeitraum?
3. Wie verteilen sich Beschreibung, Bewertung und Handlungsbedarf im Text?

## Art des Textes

Der Bildungsbericht ist ein Fachbericht mit fester Gliederung, keine Sammlung von Reden oder Interviews. Daraus folgen drei Konsequenzen für die Analyse:

- Die Kapitel A bis I folgen den Bildungsbereichen. Ein Topic Model findet diese Gliederung zu großen Teilen wieder. Aufschlussreich sind Querschnittsthemen über Kapitel hinweg und Verschiebungen innerhalb eines Kapitels. Deshalb geht das Kapitel als Kovariate ins Modell ein.
- Jeder Bericht schreibt dieselben Indikatoren fort. Ein stabiles Thema kann am Berichtskonzept liegen, nicht an einem ungelösten Problem.
- Die Sprache ist überwiegend beschreibend. Der Bericht versteht sich als Bestandsaufnahme und nicht als Sammlung von Empfehlungen.

## Ablauf des Projekts

| Schritt | Werkzeug | Ort |
|---|---|---|
| Text aus den PDFs extrahieren, bereinigen, nach Kapiteln gliedern | Python | `src` |
| Vorverarbeitung für das Topic Model | R | dieses Notebook |
| Structural Topic Model, Forschungsfrage 1 | R | `02_stm_modell.ipynb` |
| Beschreibung, Bewertung und Handlungsbedarf, Forschungsfrage 3 und erster Teil von Forschungsfrage 2 | R | `03_bewertung_handlungsbedarf.ipynb` |
| Abgleich mit den Indikatoren aus den Excel-Tabellen | folgt | `04_indikatoren.ipynb` |

## Inhalt dieses Notebooks

1. Korpus einlesen
2. Dokumente bilden
3. Sprachmodell für die Lemmatisierung laden
4. Lemmatisierung an einer Stichprobe testen
5. bis 7. Verfahren vergleichen: zwei udpipe-Modelle und Stemming
8. Ganzes Korpus lemmatisieren
9. Fehler des Sprachmodells korrigieren, Inhaltswörter auswählen, Personenbezeichnungen angleichen
10. Stämme korrigieren, häufigste Wörter prüfen
11. Vokabular bereinigen und Dokument-Wort-Matrix aufbauen

Am Ende steht eine Zusammenfassung aller Entscheidungen mit ihren Gründen und bekannten Grenzen.

## Voraussetzungen

- Die Python-Pipeline in `src` ist gelaufen und hat `data/processed/korpus_absaetze.csv` erzeugt.
- R 4.6.1 mit den Paketen `readr`, `dplyr`, `udpipe`, `quanteda` und `stm`. Das Skript `r/00_einrichtung.R` installiert sie.
- Die Sprachmodelle `german-hdt` und `german-gsd` laden Abschnitt 3 und 5 beim ersten Lauf herunter.

### 1. Korpus einlesen

Ich lese das Korpus ein, das die Python-Skripte in `src` aus den elf Berichten erzeugt haben. Die Datei enthält pro Zeile eine Einheit mit Jahr, Kapitelcode, Seite und Typ.

Für das Modell nutze ich nur die Typen `text` und `ueberschrift`. Randnotizen, Fragmente sowie Tabellen und Abbildungen bleiben in der Datei, gehen aber nicht in die Analyse ein.

In [1]:
setwd("C:/Users/c.sezgin/OneDrive - DIPF/Computational Social Sciences/bildungsbericht")
.libPaths(c(Sys.getenv("R_LIBS_USER"), .libPaths()))
suppressPackageStartupMessages({
  library(readr)
  library(dplyr)
  library(udpipe)
})

korpus <- read_csv("data/processed/korpus_absaetze.csv", show_col_types = FALSE)
table(korpus$typ)
cat("Seiten mit mindestens einer Einheit:", nrow(distinct(korpus, jahr, seite)), "\n")

         fragment         randnotiz tabelle_abbildung              text
              275              8803                 4              9188
     ueberschrift
             2596

Seiten mit mindestens einer Einheit: 2762

### 2. Dokumente bilden

Ein Dokument ist ein Textabsatz. Jede Überschrift hänge ich an den folgenden Absatz an. Überschriften allein sind zu kurz für ein Topic Model, als Teil des Absatzes bleiben sie erhalten und schärfen dessen Thema.

Technisch erhält jede Überschrift die Nummer des nächsten Textabsatzes. Folgen mehrere Überschriften aufeinander, etwa Kapitel- und Abschnittstitel, gehören alle zum selben Absatz. Die Überschriften speichere ich zusätzlich in einer eigenen Spalte, damit ich sie später getrennt auswerten kann.

In [2]:
dokumente <- korpus |>
  filter(typ %in% c("text", "ueberschrift")) |>
  mutate(absatz_id = rev(cumsum(rev(typ == "text")))) |>
  group_by(absatz_id) |>
  filter(last(typ) == "text") |>
  summarise(
    jahr = last(jahr),
    kapitel = last(kapitel),
    seite = last(seite),
    dekodiert = any(dekodiert),
    ueberschrift = paste(text[typ == "ueberschrift"], collapse = " | "),
    text = paste(text, collapse = "\n"),
    .groups = "drop"
  ) |>
  arrange(desc(absatz_id))

cat("Dokumente:", nrow(dokumente), "\n")
cat("Mit Überschrift:", sum(dokumente$ueberschrift != ""), "\n")
summary(nchar(dokumente$text))

Dokumente: 9188
Mit Überschrift: 2526

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   21.0   520.0   740.0   813.2  1024.0  6772.0

### 3. Sprachmodell für die Lemmatisierung

Lemmatisieren heißt, jedes Wort auf seine Grundform zu bringen: "Schülerinnen", "Schülern" und "Schüler" werden zu einem Lemma. Im Deutschen ist das wichtig, weil sonst jede Beugungsform als eigenes Wort zählt und das Vokabular unnötig wächst.

Ich beginne mit udpipe und dem Modell `german-hdt`. Es ist auf dem Hamburg Dependency Treebank trainiert, dem größten Baumkorpus für das Deutsche. Ob es sich für die Bildungsberichte eignet, prüfe ich in den Abschnitten 4 bis 7. Das Ergebnis vorweg: Ich verwerfe `german-hdt` zugunsten von `german-gsd`.

Das Modell wird einmal heruntergeladen und unter `data/external/udpipe` gespeichert. Bei jedem weiteren Lauf lädt die Zelle die gespeicherte Datei.

In [3]:
dir.create("data/external/udpipe", recursive = TRUE, showWarnings = FALSE)
modell_datei <- list.files("data/external/udpipe", pattern = "german-hdt.*\\.udpipe$", full.names = TRUE)
if (length(modell_datei) == 0) {
  info <- udpipe_download_model(language = "german-hdt", model_dir = "data/external/udpipe")
  modell_datei <- info$file_model
}
modell <- udpipe_load_model(modell_datei[1])
modell_datei[1]

[1] "data/external/udpipe/german-hdt-ud-2.5-191206.udpipe"

### 4. Test der Lemmatisierung an einer Stichprobe

Bevor ich alle 9.188 Dokumente verarbeite, teste ich 100 zufällig gezogene Dokumente. Der Test zeigt zwei Dinge:

1. Laufzeit: Aus der Zeit für die Stichprobe rechne ich die Dauer für das ganze Korpus hoch.
2. Qualität: 20 Substantive aus der Stichprobe mit ihrem Lemma zeigen, ob die Grundformen stimmen. Ich zeige einzelne Wörter statt fortlaufenden Text, damit das Notebook keine Sätze aus den Berichten ausgibt.

Die Satzanalyse (Dependenzparser) schalte ich ab. Das Topic Model braucht nur Lemma und Wortart, der Parser würde die Laufzeit vervielfachen.

In [4]:
set.seed(1)
probe <- slice_sample(dokumente, n = 100)
zeit <- system.time(
  anno <- udpipe(x = probe$text, object = modell, doc_id = probe$absatz_id, parser = "none")
)
minuten <- zeit[["elapsed"]] / sum(nchar(probe$text)) * sum(nchar(dokumente$text)) / 60
cat("Probe:", round(zeit[["elapsed"]], 1), "Sekunden\n")
cat("Hochrechnung ganzes Korpus:", round(minuten), "Minuten\n\n")
anno |>
  filter(upos == "NOUN", nchar(token) > 3) |>
  distinct(token, lemma) |>
  head(20)

Probe: 5.1 Sekunden
Hochrechnung ganzes Korpus: 8 Minuten

   token            lemma
1  Gymnasiasten     Dienst
2  Jahrgangsstufe   Stufe
3  Teil             Teil
4  Sekundarbereichs Bereich
5  Versetzung       Versetzung
6  Ländern          Land
7  Verbindung       Verbindung
8  Abschlussprüfung Abschlussprüfung
9  Ende             Ende
10 Oberstufe        Oberstufe
11 Gymnasiums       Gymnasium
12 Schüler          Schüler
13 Schulart         Schulart
14 Realschule       Realschule
15 Gesamtschule     Schule
16 Sekundarbereich  Bereich
17 Viertel          Viertel
18 Gesamtschüler    Gesamtschüler
19 Schuljahres      Schuljahr
20 Realschulen      Schule

### 5. Vergleich: Lemmatisierung und Stemming

Die Durchsicht der Lemmata zeigt ein Problem: Das Modell `german-hdt` kürzt Komposita auf den letzten Bestandteil ("Jahrgangsstufe" zu "Stufe", "Sekundarbereichs" zu "Bereich") und liefert teils falsche Lemmata ("Gymnasiasten" zu "Dienst"). Für eine inhaltliche Analyse ist das schädlich, weil im Deutschen gerade die Komposita den Inhalt tragen.

Ich vergleiche drei Varianten an derselben Stichprobe:

1. `german-hdt`: bisheriges udpipe-Modell
2. `german-gsd`: zweites udpipe-Modell mit anderen Trainingsdaten
3. Stemming nach Snowball: Wortstamm per Regel, erhält Komposita immer

Als Maß dient der Anteil der Substantive, deren Grundform weniger als 60 Prozent der Wortlänge hat und mit anderen Buchstaben beginnt. Solche Fälle sind vermutlich abgeschnittene Komposita.

In [5]:
# Zweites Modell laden
gsd_datei <- list.files("data/external/udpipe", pattern = "german-gsd.*\\.udpipe$", full.names = TRUE)
if (length(gsd_datei) == 0) {
  info <- udpipe_download_model(language = "german-gsd", model_dir = "data/external/udpipe")
  gsd_datei <- info$file_model
}
modell_gsd <- udpipe_load_model(gsd_datei[1])
anno_gsd <- udpipe(x = probe$text, object = modell_gsd, doc_id = probe$absatz_id, parser = "none")

ohne_umlaut <- function(x) chartr("äöü", "aou", tolower(x))

abgeschnitten <- function(token, grundform) {
  nchar(grundform) < 0.6 * nchar(token) &
    substr(ohne_umlaut(token), 1, 2) != substr(ohne_umlaut(grundform), 1, 2)
}

vergleiche <- function(a, name) {
  n <- a[a$upos == "NOUN" & nchar(a$token) > 3, ]
  treffer <- abgeschnitten(n$token, n$lemma)
  cat(sprintf("%s: %d Substantive, davon abgeschnitten %.1f Prozent\n",
              name, nrow(n), 100 * mean(treffer)))
  beispiele <- unique(paste(n$token[treffer], "->", n$lemma[treffer]))
  cat("  Beispiele:", paste(head(beispiele, 12), collapse = "; "), "\n\n")
}

vergleiche(anno, "german-hdt")
vergleiche(anno_gsd, "german-gsd")

# Stemming auf die Substantive aus german-gsd
n <- anno_gsd[anno_gsd$upos == "NOUN" & nchar(anno_gsd$token) > 3, ]
stamm <- SnowballC::wordStem(tolower(n$token), language = "german")
cat("Stemming, Beispiele:\n")
beispiel <- unique(paste(n$token, "->", stamm))
cat(" ", paste(head(beispiel[nchar(n$token[!duplicated(paste(n$token, "->", stamm))]) > 10], 15),
               collapse = "; "), "\n")

german-hdt: 2704 Substantive, davon abgeschnitten 12.9 Prozent
  Beispiele: Gymnasiasten -> Dienst; Jahrgangsstufe -> Stufe; Sekundarbereichs -> Bereich; Gesamtschule -> Schule; Sekundarbereich -> Bereich; Realschulen -> Schule; Autor:innengruppe -> Gruppe; Ländergruppe -> Gruppe; Schularten -> Karte; Fachgymnasien -> unknown; Grundinformationen -> Funktion; Hochschulbildung -> Bildung

german-gsd: 2718 Substantive, davon abgeschnitten NA Prozent
  Beispiele: NA -> NA

Stemming, Beispiele:
  Gymnasiasten -> gymnasiast; Jahrgangsstufe -> jahrgangsstuf; Abschlussprüfung -> abschlusspruf; Gesamtschule -> gesamtschul; Sekundarbereich -> sekundarbereich; Gesamtschüler -> gesamtschul; Schuljahres -> schuljahr; Realschulen -> realschul; Hauptschulen -> hauptschul; Gesamtschulen -> gesamtschul; Schülerinnen -> schulerinn; Hochschulreife -> hochschulreif; Ausscheiden -> ausscheid; Jugendlichen -> jugend; Arbeitslosigkeit -> arbeitslos

### 6. Prüfung von german-gsd und Test kritischer Wörter

Das Modell `german-gsd` liefert für einen Teil der Wörter kein Lemma (NA). Ich prüfe, wie groß dieser Anteil ist und ob die vorhandenen Lemmata stimmen.

Stemming erhält zwar Komposita, legt aber verschiedene Begriffe zusammen: "Gesamtschüler" und "Gesamtschule" werden beide zu "gesamtschul". Ein gezielter Testsatz mit Wortpaaren, die im Bildungsbericht getrennt bleiben müssen, zeigt die Stärken und Schwächen aller drei Varianten: Schüler und Schule, Lehrer und Lehre, Komposita wie Jahrgangsstufe und Sekundarbereich.

In [6]:
cat("german-gsd: Wörter ohne Lemma:", sum(is.na(anno_gsd$lemma)), "von", nrow(anno_gsd),
    sprintf("(%.1f Prozent)\n\n", 100 * mean(is.na(anno_gsd$lemma))))

n_gsd <- anno_gsd[anno_gsd$upos == "NOUN" & nchar(anno_gsd$token) > 3 & !is.na(anno_gsd$lemma), ]
treffer <- abgeschnitten(n_gsd$token, n_gsd$lemma)
cat(sprintf("german-gsd ohne NA: %d Substantive, davon abgeschnitten %.1f Prozent\n",
            nrow(n_gsd), 100 * mean(treffer)))
cat("  Beispiele:", paste(head(unique(paste(n_gsd$token[treffer], "->", n_gsd$lemma[treffer])), 12),
                          collapse = "; "), "\n\n")

testsatz <- paste("Die Schülerinnen und Schüler der Gesamtschulen sowie die Lehrerinnen,",
                  "Lehrer und Lehrkräfte berichten über die duale Lehre, die Jahrgangsstufen",
                  "im Sekundarbereich und die Bildungsverläufe der Jugendlichen.")
t_hdt <- udpipe(testsatz, modell, parser = "none")
t_gsd <- udpipe(testsatz, modell_gsd, parser = "none")
data.frame(
  token = t_hdt$token,
  hdt = t_hdt$lemma,
  gsd = if (nrow(t_gsd) == nrow(t_hdt)) t_gsd$lemma else NA,
  stemming = SnowballC::wordStem(tolower(t_hdt$token), language = "german")
)

german-gsd: Wörter ohne Lemma: 197 von 12704 (1.6 Prozent)

german-gsd ohne NA: 2709 Substantive, davon abgeschnitten 0.0 Prozent
  Beispiele:  ->

   token            hdt             gsd stemming
1  Die              Die             NA  die
2  Schülerinnen     Schülerin       NA  schulerinn
3  und              und             NA  und
4  Schüler          Schüler         NA  schul
5  der              der             NA  der
6  Gesamtschulen    Gesamtschule    NA  gesamtschul
7  sowie            sowie           NA  sowi
8  die              die             NA  die
9  Lehrerinnen      Lehrerin        NA  lehrerinn
10 ,                ,               NA  ,
11 Lehrer           Lehrer          NA  lehr
12 und              und             NA  und
13 Lehrkräfte       Lehrkraft       NA  lehrkraft
14 berichten        berichten       NA  bericht
15 über             über            NA  uber
16 die              die             NA  die
17 duale            dual            NA  dual
18 Lehre            Lehre           NA  lehr
19 ,                ,               NA  ,
20 die              die             NA  die
21 Jahrgangsstufen  Stufe           NA  jahrgangsstuf
22 im               im              NA  im
23 Sekundarbereich  Bereich         NA  sekundarbereich
24 und              und             NA  und
25 die              die             NA  die
26 Bildungsverläufe Bildungsverlauf NA  bildungsverlauf
27 der              der             NA  der
28 Jugendlichen     Jugendlich      NA  jugend
29 .                .               NA  .

### 7. Testsatz mit german-gsd

`german-gsd` lässt nur 1,6 Prozent der Wörter ohne Lemma und schneidet kein Kompositum ab. Stemming scheidet aus, weil es "Schüler" und "Schule" sowie "Lehrer" und "Lehre" zusammenlegt.

Im Vergleich oben fehlte das gsd-Ergebnis, weil das Modell den Testsatz in eine andere Anzahl von Wörtern zerlegt. Hier steht es getrennt.

In [7]:
t_gsd[, c("token", "lemma", "upos")]

   token            lemma           upos
1  Die              der             DET
2  Schülerinnen     Schülerin       NOUN
3  und              und             CCONJ
4  Schüler          Schüler         NOUN
5  der              der             DET
6  Gesamtschulen    Gesamtschule    NOUN
7  sowie            sowie           CCONJ
8  die              der             DET
9  Lehrerinnen      Lehrerinnen     NOUN
10 ,                ,               PUNCT
11 Lehrer           Lehrer          NOUN
12 und              und             CCONJ
13 Lehrkräfte       Lehrkraft       NOUN
14 berichten        berichten       VERB
15 über             über            ADP
16 die              der             DET
17 duale            dual            ADJ
18 Lehre            Lehre           NOUN
19 ,                ,               PUNCT
20 die              der             DET
21 Jahrgangsstufen  Jahrgangsstufen NOUN
22 im               NA              NA
23 in               in              ADP
24 dem              der             DET
25 Sekundarbereich  Sekundarbereich NOUN
26 und              und             CCONJ
27 die              der             DET
28 Bildungsverläufe Bildungsverlauf NOUN
29 der              der             DET
30 Jugendlichen     Jugendliche     NOUN
31 .                .               PUNCT

### 8. Lemmatisierung des ganzen Korpus mit german-gsd

Entscheidung: Ich lemmatisiere mit `german-gsd`.

- `german-hdt` scheidet aus: 12,9 Prozent der Substantive werden auf den letzten Bestandteil gekürzt oder falsch lemmatisiert ("Schularten" zu "Karte").
- Stemming scheidet aus: Es legt verschiedene Begriffe zusammen ("Schüler" und "Schule" zu "schul", "Lehrer" und "Lehre" zu "lehr").
- `german-gsd` erhält Komposita und trennt diese Wortpaare korrekt. Jedes Wort erhält ein Lemma. Die Zeilen ohne Lemma sind ausschließlich Klammerzeilen für zusammengezogene Wörter wie "im" (= "in" + "dem"), deren Teile eigene Zeilen haben.

Das Ergebnis speichere ich als RDS-Datei unter `data/interim`. Spätere Schritte laden diese Datei, statt die Lemmatisierung zu wiederholen.

In [8]:
zeit <- system.time(
  anno_alle <- udpipe(x = dokumente$text, object = modell_gsd,
                      doc_id = dokumente$absatz_id, parser = "none")
)
anno_alle <- anno_alle[, c("doc_id", "sentence_id", "token_id", "token", "lemma", "upos")]

saveRDS(anno_alle, "data/interim/udpipe_gsd.rds")
saveRDS(dokumente, "data/interim/dokumente.rds")

cat("Laufzeit:", round(zeit[["elapsed"]] / 60, 1), "Minuten\n")
cat("Wörter:", nrow(anno_alle), "\n")
cat("Ohne Lemma:", sprintf("%.1f Prozent\n", 100 * mean(is.na(anno_alle$lemma))))
table(anno_alle$upos, useNA = "ifany")

Laufzeit: 9.9 Minuten
Wörter: 1137415
Ohne Lemma: 1.6 Prozent

   ADJ    ADP    ADV    AUX  CCONJ    DET   NOUN    NUM   PART   PRON  PROPN
112687 141976  58992  30066  40919 137060 248358  30187   8443  38581  39324
 PUNCT  SCONJ    SYM   VERB      X   <NA>
150896   8135    800  65270   6978  18743

### 9. Fehler des Sprachmodells korrigieren, Inhaltswörter auswählen, Personenbezeichnungen angleichen

Aus den lemmatisierten Wörtern bilde ich das Vokabular für das Topic Model in vier Schritten:

1. Zeilen ohne Wortart entfernen. Das sind die Klammern um zusammengezogene Wörter wie "im" (= "in" + "dem"), deren Teile bereits eigene Zeilen haben.
2. Fehler des Sprachmodells korrigieren, die erste Testmodelle sichtbar gemacht haben:
   - Abkürzungen mit Punkt lemmatisiert das Modell zu Phantasiewörtern: "al." aus "et al." zu "alienisch", "vgl." zu "vglienisch". Ich entferne alle Wortformen aus höchstens fünf Buchstaben mit Punkt am Ende ("vgl.", "al.", "bzw.", "z.", "B.", "ca."). Satzzeichen am Satzende stehen bei udpipe als eigene Zeile und sind davon nicht betroffen.
   - Komposita mit Bindestrich zerlegt udpipe in Teile ("Lehr-Lern-Prozesse" in "Lehr", "-", "Lern", "-", "Prozesse"). Für Bruchstücke wie "Lern" erzeugt es falsche Lemmata ("Ler"). Folgt auf ein Wort ein Bindestrich und kommt sein Lemma sonst nicht als eigenständiges Wort vor, nehme ich die Wortform. Richtige Lemmata wie "Kind" in "Kinder- und Jugendhilfe" bleiben erhalten.
3. Nur Inhaltswörter behalten: Substantive, Eigennamen, Adjektive und Verben.
4. Personenbezeichnungen angleichen. Die Berichte wechseln über die Jahre die Genderschreibweise: "Schülerinnen und Schüler", "SchülerInnen", "Schüler:innen". Ohne Angleichung würde das Modell diesen Stilwechsel als Themenwandel messen. Ich führe alle Formen auf eine gemeinsame Messform zurück, etwa "Schüler". Das dient nur der Messung, nicht der Sprache im Bericht.

Regel für Schritt 4:
- Formen mit Genderzeichen (":innen", "*in", "_innen", "Innen") verlieren das Suffix.
- Formen auf "-in" oder "-innen" verlieren das Suffix nur, wenn der verbleibende Stamm selbst als Substantiv im Korpus vorkommt. So wird "Lehrerin" zu "Lehrer", aber "Disziplin" oder "Medizin" bleiben unverändert.

Die Ausgabe zeigt die entfernten Abkürzungen, die ersetzten Wortteile und die 30 häufigsten Angleichungen zur Prüfung.

In [9]:
abkuerzung <- grepl("^[[:alpha:]]{1,5}\\.$", anno_alle$token)
cat("Abkürzungen mit Punkt entfernt:", sum(abkuerzung), "\n")
print(head(sort(table(anno_alle$token[abkuerzung]), decreasing = TRUE), 15))

anno <- anno_alle[!abkuerzung, ] |>
  filter(!is.na(upos)) |>
  group_by(doc_id) |>
  mutate(naechstes = lead(token)) |>
  ungroup() |>
  mutate(
    lemma = ifelse(is.na(lemma), token, lemma),
    vor_strich = !is.na(naechstes) & naechstes == "-"
  )

# Lemmata, die als eigenständiges Wort mindestens 5 Mal vorkommen
eigenstaendig <- anno |> filter(!vor_strich) |> count(lemma) |> filter(n >= 5) |> pull(lemma)

# Wortteil vor Bindestrich: Wortform nur, wenn das Lemma sonst nicht vorkommt
ersetzen <- anno$vor_strich & !anno$lemma %in% eigenstaendig
cat("\nWortteile vor Bindestrich:", sum(anno$vor_strich), "\n")
cat("Davon Lemma durch Wortform ersetzt:", sum(ersetzen), "\n")
anno$lemma[ersetzen] <- anno$token[ersetzen]

inhalt <- anno |> filter(upos %in% c("NOUN", "PROPN", "ADJ", "VERB"))

# Stufe a: explizite Genderzeichen entfernen
ohne_zeichen <- sub("[:*_](in|innen)$", "", inhalt$lemma)
ohne_zeichen <- sub("(?<=[a-zäöüß])In(nen)?$", "", ohne_zeichen, perl = TRUE)

# Stufe b: -in / -innen nur entfernen, wenn der Stamm als Substantiv vorkommt
substantive <- table(ohne_zeichen[inhalt$upos %in% c("NOUN", "PROPN")])
bekannt <- names(substantive)[substantive >= 5]
stamm <- sub("(in|innen)$", "", ohne_zeichen)
angleichen <- inhalt$upos %in% c("NOUN", "PROPN") &
  stamm != ohne_zeichen & nchar(stamm) >= 3 & stamm %in% bekannt
inhalt$wort <- ifelse(angleichen, stamm, ohne_zeichen)

geaendert <- inhalt$wort != inhalt$lemma
cat("\nInhaltswörter:", nrow(inhalt), "\n")
cat("Angeglichen:", sum(geaendert), sprintf("(%.1f Prozent)\n\n", 100 * mean(geaendert)))

inhalt |>
  filter(wort != lemma) |>
  count(lemma, wort, sort = TRUE) |>
  head(30)

Abkürzungen mit Punkt entfernt: 6089

 vgl.  Abb.   al.    B.    z.    S.    u.   vs.  ebd.    h.    a.    d.   ca.
 1253  1231   964   863   577   338   307    80    73    65    59    51    31
   I. bspw.
   21    20

Wortteile vor Bindestrich: 12374
Davon Lemma durch Wortform ersetzt: 3500

Inhaltswörter: 462407
Angeglichen: 3725 (0.8 Prozent)

   lemma                      wort                 n
1  Schülerin                  Schüler              726
2  Schüler:innen              Schüler              455
3  Absolventinnen             Absolvent            194
4  Studienanfängerinnen       Studienanfänger      139
5  Absolvent:innen            Absolvent            104
6  Akteur:innen               Akteur                98
7  Hochschulabsolventinnen    Hochschulabsolvent    98
8  Studienanfänger:innen      Studienanfänger       95
9  Bildungsteilnehmerinnen    Bildungsteilnehmer    85
10 Teilnehmerin               Teilnehmer            59
11 Hochschulabsolvent:innen   Hochschulabsolvent    58
12 Erzieherin                 Erzieher              52
13 Bachelorabsolvent:innen    Bachelorabsolvent     42
14 Ausbildungsabsolvent:innen Ausbildungsabsolvent  31
15 Anfänger:innen             Anfänger              30
16 Erzieher:innen             Erzieher              30
17 Ausländerinnen             Ausländer             29
18 Akademikerinnen            Akademiker            27
19 Lehrerin                   Lehrer                27
20 Rentner:innen              Rentner               26
21 Ausbilder:innen            Ausbilder             25
22 Bachelorabsolventinnen     Bachelorabsolvent     25
23 Bewerber:innen             Bewerber              25
24 Lehrer:innen               Lehrer                24
25 Bildungsteilnehmerin       Bildungsteilnehmer    23
26 Schulabgänger:innen        Schulabgänger         22
27 Schulabgängerinnen         Schulabgänger         22
28 Abiturientinnen            Abiturient            21
29 Professor:innen            Professor             21
30 Arbeitnehmerinnen          Arbeitnehmer          20

### 10. Korrektur der Stämme und häufigste Wörter

Die 30 häufigsten Angleichungen in Abschnitt 9 sind korrekt. Fehler zeigen sich eher bei seltenen Wörtern. Deshalb prüfe ich zuerst eine Zufallsstichprobe von 25 Angleichungen, die höchstens dreimal vorkommen.

Die Stichprobe zeigt eine Ungenauigkeit: Bei Wörtern, deren männliche Form auf "-e" endet, bleibt ein verkürzter Stamm ("Weiterbildungspädagog:in" wird "Weiterbildungspädagog"). Kommt der Stamm mit angehängtem "e" mindestens fünfmal im Korpus vor, verwende ich diese Form ("Pädagog:innen" wird "Pädagoge", "Kolleg:innen" wird "Kollege"). Seltene Komposita bleiben verkürzt, weil ihre Form mit "e" zu selten vorkommt, um sie sicher zu bestätigen.

Danach zeige ich die 50 Wörter, die in den meisten Dokumenten vorkommen. Wörter wie "Anteil", "Prozent" oder "Jahr" stehen in einem indikatorengestützten Bericht in fast jedem Absatz. Sie unterscheiden keine Themen. Aus dieser Liste leite ich ab, welche berichtstypischen Wörter ich als zusätzliche Stoppwörter entferne.

In [10]:
# Stichprobe seltener Angleichungen
set.seed(2)
print(inhalt |>
        filter(wort != lemma) |>
        count(lemma, wort) |>
        filter(n <= 3) |>
        slice_sample(n = 25),
      n = 25)

# Verkürzte Stämme ergänzen: "Pädagog" zu "Pädagoge", wenn die Form mit e vorkommt
mit_e <- paste0(inhalt$wort, "e")
ergaenzen <- inhalt$wort != inhalt$lemma & mit_e %in% bekannt
inhalt$wort[ergaenzen] <- mit_e[ergaenzen]
cat("\nStämme mit e ergänzt:", sum(ergaenzen), "\n")
print(inhalt |> filter(ergaenzen) |> count(lemma, wort, sort = TRUE) |> head(10))

# Häufigste Wörter nach Zahl der Dokumente
n_dokumente <- nrow(dokumente)
inhalt$wort_klein <- tolower(inhalt$wort)
haeufig <- inhalt |>
  group_by(wort_klein) |>
  summarise(n = n(), in_dokumenten = n_distinct(doc_id), .groups = "drop") |>
  mutate(anteil = round(in_dokumenten / n_dokumente, 3)) |>
  arrange(desc(in_dokumenten)) |>
  head(50)
print(haeufig, n = 50)

# A tibble: 25 × 3
   lemma                        wort                       n
   <chr>                        <chr>                  <int>
 1 Kommiliton:innen             Kommiliton                 1
 2 Analphabet:innen             Analphabet                 3
 3 Technikerin                  Techniker                  1
 4 Realschüler:innen            Realschüler                2
 5 Ausbildungsakquisiteur:innen Ausbildungsakquisiteur     1
 6 Laborant:innen               Laborant                   1
 7 Patient:innen                Patient                    1
 8 Dozent:innen                 Dozent                     3
 9 Weiterbildungspädagog:in     Weiterbildungspädagog      1
10 Inklusionshelfer:innen       Inklusionshelfer           1
11 Primarschüler:innen          Primarschüler              3
12 Fachhochschulabsolvent:innen Fachhochschulabsolvent     3
13 Nebenberufler:innen          Nebenberufler              1
14 Fleischer:in                 Fleischer                  1
15 Ganztagsschülerinnen         Ganztagsschüler            1
16 schülerin                    schüler                    1
17 Bildungsaufsteiger:innen     Bildungsaufsteiger         2
18 Fachwirt:in                  Fachwirt                   2
19 Logopäd:innen                Logopäd                    1
20 Migrant:innen                Migrant                    3
21 Bürger:innen                 Bürger                     2
22 Vollzeitschüler:innen        Vollzeitschüler            2
23 Meisterin                    Meister                    1
24 Schulaufsichtsbeamt:innen    Schulaufsichtsbeamt        1
25 Erstklässler:innen           Erstklässler               3

Stämme mit e ergänzt: 21
# A tibble: 4 × 3
  lemma              wort              n
  <chr>              <chr>         <int>
1 Kolleginnen        Kollege          11
2 Kolleg:innen       Kollege           8
3 Altersgenoss:innen Altersgenosse     1
4 Pädagog:innen      Pädagoge          1
# A tibble: 50 × 4
   wort_klein                n in_dokumenten anteil
   <chr>                 <int>         <int>  <dbl>
 1 tab                    5211          3278  0.357
 2 jahr                   5036          3046  0.332
 3 hoch                   4087          2751  0.299
 4 anteil                 3284          2038  0.222
 5 deutlich               2453          1997  0.217
 6 kind                   4239          1833  0.199
 7 zeigen                 2085          1821  0.198
 8 bildung                2701          1788  0.195
 9 beruflich              2672          1670  0.182
10 %                      4934          1629  0.177
11 liegen                 1847          1560  0.17
12 entwicklung            1928          1507  0.164
13 stark                  1727          1469  0.16
14 groß                   1601          1384  0.151
15 schule                 2319          1379  0.15
16 deutschland            1925          1373  0.149
17 land                   2157          1347  0.147
18 person                 2101          1164  0.127
19 unterschiedlich        1331          1141  0.124
20 ausbildung             1799          1135  0.124
21 haben                  1253          1127  0.123
22 gering                 1439          1125  0.122
23 sozial                 1636          1107  0.12
24 lassen                 1194          1092  0.119
25 angebot                1594          1085  0.118
26 häufig                 1387          1075  0.117
27 unterschied            1304          1064  0.116
28 weit                   1162          1049  0.114
29 jugendliche            1633           991  0.108
30 ander                  1081           981  0.107
31 vergleich              1162           981  0.107
32 letzt                  1071           962  0.105
33 abschluß               1473           954  0.104
34 abb                    1041           946  0.103
35 geben                  1050           944  0.103
36 bereich                1099           894  0.097
37 bleiben                 960           868  0.094
38 weiterbildung          1738           863  0.094
39 niedrig                1041           857  0.093
40 stellen                 916           850  0.093
41 steigen                 962           842  0.092
42 neu                     994           828  0.09
43 schüler                2060           827  0.09
44 hochschule             1356           810  0.088
45 zahl                   1094           806  0.088
46 gut                     880           747  0.081
47 gruppe                  967           738  0.08
48 jung                    959           722  0.079
49 migrationshintergrund  1393           716  0.078
50 nehmen                  767           712  0.077

### 11. Vokabular bereinigen und Dokument-Wort-Matrix aufbauen

Die häufigsten Wörter zeigen drei Probleme, die ich hier behebe:

1. Verweisreste wie "tab", "abb" und "%" aus Verweisen auf Tabellen und Abbildungen entferne ich.
2. `german-gsd` lemmatisiert teils in alter Rechtschreibung ("Abschluss" zu "Abschluß"). Im Messvokabular schreibe ich "ß" deshalb einheitlich als "ss".
3. Berichtstypische Wörter, die Größen und Veränderungen beschreiben, aber kein Thema ("jahr", "anteil", "hoch", "deutlich", "zeigen", "steigen"), entferne ich über eine eigene Stoppwortliste, zusätzlich zur deutschen Standardliste. Inhaltlich tragende Wörter wie "kind", "schule" oder "migrationshintergrund" bleiben, auch wenn sie häufig sind.

Die Liste umfasst 48 Wörter. Zehn davon habe ich nach Durchsicht der 40 häufigsten Wörter einer ersten Matrix ergänzt, darunter "nehmen", "bestehen", "wichtig" und "bereich". "weisen" stammt aus trennbaren Verben wie "weisen ... auf", "jährigen" aus Altersangaben wie "15-Jährigen".

Außerdem entferne ich Wörter mit Ziffern oder Satzzeichen, Wörter unter drei Buchstaben und Wörter, die in weniger als 10 Dokumenten vorkommen. Seltene Wörter tragen zur Themenbildung kaum bei und vergrößern nur das Modell.

Das Ergebnis ist eine Dokument-Wort-Matrix mit Jahr und Kapitel als Metadaten. Ich speichere sie im Format des Pakets `stm`.

In [11]:
suppressPackageStartupMessages(library(quanteda))

berichtswoerter <- c(
  "tab", "abb", "prozent", "jahr", "anteil", "zahl", "vergleich", "insgesamt",
  "hoch", "deutlich", "stark", "gross", "gering", "häufig", "weit", "ander",
  "letzt", "niedrig", "neu", "gut", "unterschiedlich", "jeweils", "rund",
  "zeigen", "liegen", "haben", "lassen", "geben", "bleiben", "stellen",
  "steigen", "sinken", "gehen", "kommen", "finden", "sehen", "nennen", "betragen",
  "nehmen", "bestehen", "teil", "wichtig", "stehen", "weisen", "blick",
  "aktuell", "bereich", "jährigen"
)
stopp <- c(gsub("ß", "ss", stopwords("de")), berichtswoerter)

inhalt$mess <- gsub("ß", "ss", inhalt$wort_klein)
behalten <- grepl("^[a-zäöü][a-zäöü-]*[a-zäöü]$", inhalt$mess) &
  nchar(inhalt$mess) >= 3 &
  !inhalt$mess %in% stopp
cat("Wörter nach Bereinigung:", sum(behalten), "von", nrow(inhalt), "\n")

# Tokens pro Dokument in der Reihenfolge der Tabelle dokumente
ids <- factor(inhalt$doc_id[behalten], levels = as.character(dokumente$absatz_id))
tokens_liste <- split(inhalt$mess[behalten], ids)
dfm_alle <- dfm(as.tokens(tokens_liste))
docvars(dfm_alle, "jahr") <- dokumente$jahr
docvars(dfm_alle, "kapitel") <- dokumente$kapitel
docvars(dfm_alle, "dekodiert") <- dokumente$dekodiert
cat("Matrix vor Kürzung:", ndoc(dfm_alle), "Dokumente,", nfeat(dfm_alle), "Wörter\n")

dfm_modell <- dfm_trim(dfm_alle, min_docfreq = 10, docfreq_type = "count")
dfm_modell <- dfm_subset(dfm_modell, ntoken(dfm_modell) >= 5)
cat("Matrix nach Kürzung:", ndoc(dfm_modell), "Dokumente,", nfeat(dfm_modell), "Wörter\n\n")

stm_daten <- convert(dfm_modell, to = "stm")
saveRDS(stm_daten, "data/interim/stm_daten.rds")

cat("Häufigste Wörter nach Dokumenten:\n")
print(topfeatures(dfm_modell, 40, scheme = "docfreq"))

Wörter nach Bereinigung: 377957 von 462407
Matrix vor Kürzung: 9188 Dokumente, 25125 Wörter
Matrix nach Kürzung: 9125 Dokumente, 4241 Wörter

Häufigste Wörter nach Dokumenten:
                 kind               bildung             beruflich
                 1833                  1784                  1669
          entwicklung                schule           deutschland
                 1507                  1378                  1370
                 land                person            ausbildung
                 1344                  1163                  1133
               sozial               angebot           unterschied
                 1106                  1084                  1064
          jugendliche             abschluss         weiterbildung
                  988                   954                   859
              schüler            hochschule                gruppe
                  826                   809                   738
                 jung migrationshintergrund             bedeutung
                  722                   715                   700
              deutsch                  früh                eltern
                  681                   661                   659
            erreichen            öffentlich           pädagogisch
                  655                   639                   623
             personal         international               studium
                  618                   611                   605
           betrachten      allgemeinbildend           individuell
                  587                   580                   578
                 erst                mensch               familie
                  578                   578                   572
                beruf             schulisch                  frau
                  566                   564                   559
            zunehmend
                  548

## Zusammenfassung der Vorverarbeitung

### Ziel

Dieses Notebook bereitet die elf Bildungsberichte "Bildung in Deutschland" (2006 bis 2026) für ein Structural Topic Model vor. Der Fokus der Analyse liegt auf Inhalten, nicht auf Formulierungen oder Stil. Alle Entscheidungen zielen darauf, stilistische Unterschiede zwischen den Jahrgängen aus der Messung herauszuhalten.

### Ausgangsdaten

Grundlage ist `data/processed/korpus_absaetze.csv` aus der Python-Pipeline in `src`. Sie umfasst die Berichte von der Einleitung bis vor das Literaturverzeichnis, 2.762 Seiten enthalten mindestens eine Einheit. Die Datei enthält 9.188 Textabsätze, 2.596 Überschriften sowie Randnotizen, Fragmente und Tabellentitel. Nur Textabsätze und Überschriften gehen in die Analyse ein.

### Schritte und Entscheidungen

**1. Dokumente bilden.** Ein Dokument ist ein Textabsatz. Überschriften hänge ich an den folgenden Absatz an, weil sie allein zu kurz für ein Topic Model sind. Ergebnis: 9.188 Dokumente, davon 2.526 mit Überschrift, im Median 740 Zeichen.

**2. Lemmatisierung.** Ich habe drei Verfahren an einer Stichprobe von 100 Dokumenten verglichen:

| Verfahren | Ergebnis | Entscheidung |
|---|---|---|
| udpipe `german-hdt` | kürzt 12,9 Prozent der Substantive auf den letzten Bestandteil ("Jahrgangsstufe" zu "Stufe") | verworfen |
| Stemming (Snowball) | legt verschiedene Begriffe zusammen ("Schüler" und "Schule" zu "schul", "Lehrer" und "Lehre" zu "lehr") | verworfen |
| udpipe `german-gsd` | erhält Komposita und trennt die kritischen Wortpaare, jedes Wort erhält ein Lemma | gewählt |

Die Lemmatisierung des ganzen Korpus dauerte je nach Auslastung des Rechners 8 bis 22 Minuten. Sie ergab 1.137.415 Zeilen, davon 18.743 Klammerzeilen für zusammengezogene Wörter wie "im" (= "in" + "dem"). Deren Teile stehen in eigenen Zeilen, die Klammerzeilen entferne ich.

**3. Korrektur von Fehlern des Sprachmodells.** Erste Testmodelle in `02_stm_modell.ipynb` zeigten Phantasiewörter und Bruchstücke im Vokabular. Sie haben zwei Ursachen, die ich hier korrigiere:

- Abkürzungen mit Punkt lemmatisiert das Modell zu Phantasiewörtern: "al." aus "et al." zu "alienisch", "vgl." zu "vglienisch". Ich entferne alle Wortformen aus höchstens fünf Buchstaben mit Punkt am Ende. Das betrifft 6.089 Wortformen, vor allem "vgl.", "Abb.", "al.", "z. B.", "S." und "u.".
- Komposita mit Bindestrich zerlegt udpipe in Teile und erzeugt für Bruchstücke falsche Lemmata ("Lern" zu "Ler"). Folgt auf ein Wort ein Bindestrich und kommt sein Lemma sonst nicht als eigenständiges Wort vor, ersetze ich das Lemma durch die Wortform. Das betrifft 3.500 von 12.374 Wortteilen vor einem Bindestrich. Richtige Lemmata wie "Kind" in "Kinder- und Jugendhilfe" bleiben erhalten.

**4. Inhaltswörter.** Ich behalte Substantive, Eigennamen, Adjektive und Verben: 462.407 Wörter.

**5. Angleichung der Personenbezeichnungen.** Die Berichte wechseln die Genderschreibweise ("Schülerinnen und Schüler", "Schüler:innen"). Damit das Modell diesen Stilwechsel nicht als Themenwandel misst, führe ich alle Formen auf eine gemeinsame Messform zurück. Formen auf "-in" oder "-innen" gleiche ich nur an, wenn der Stamm im Korpus als Substantiv vorkommt ("Lehrerin" zu "Lehrer", aber "Disziplin" bleibt). Endet die männliche Form auf "-e", ergänze ich das "e" ("Kolleg:innen" zu "Kollege"). Betroffen sind 3.725 Wörter (0,8 Prozent).

**6. Bereinigung des Vokabulars.**
- "ß" schreibe ich als "ss", weil `german-gsd` teils in alter Rechtschreibung lemmatisiert ("Abschluß").
- Entfernt werden die deutsche Standard-Stoppwortliste und 48 berichtstypische Wörter, die Größen und Veränderungen beschreiben, aber kein Thema ("jahr", "anteil", "hoch", "deutlich", "steigen"), sowie Verweisreste ("tab", "abb").
- Entfernt werden Wörter mit Ziffern oder Satzzeichen und Wörter unter drei Buchstaben.

Nach der Bereinigung bleiben 377.957 Wörter.

**7. Dokument-Wort-Matrix.** Ich behalte Wörter, die in mindestens 10 Dokumenten vorkommen, und Dokumente mit mindestens 5 Wörtern. Ergebnis: 9.125 Dokumente und 4.241 Wörter, mit Jahr und Kapitel als Metadaten.

### Bekannte Grenzen

- Beschreibt der Bericht Geschlechterunterschiede ("Schülerinnen erreichen höhere Werte als Schüler"), geht dieser Kontrast durch die Angleichung verloren. Das Thema Geschlecht bleibt über Wörter wie "Mädchen", "Jungen", "Frauen" und "Geschlecht" erkennbar.
- Komposita mit Bindestrich zerfallen in ihre Teile ("Lehr-Lern-Prozesse" in "lehr", "lern", "prozess"). Das gilt auch für Ländernamen wie "Baden-Württemberg".
- `german-gsd` führt einzelne Pluralformen nicht auf den Singular zurück ("Jahrgangsstufen").
- Bei trennbaren Verben geht die Vorsilbe verloren ("weisen ... auf" wird "weisen").
- Autorennamen aus Literaturverweisen bleiben als Eigennamen im Vokabular, sofern sie in mindestens 10 Dokumenten vorkommen.
- 35 Absätze aus 2014 stammen aus einer defekt kodierten Schrift und wurden in der Python-Pipeline dekodiert. Sie sind in der Spalte `dekodiert` markiert und erlauben eine Kontrollrechnung ohne sie. Im Überblicksteil 2014 wurden Aufzählungspunkte deshalb nicht getrennt, er besteht aus nur 13 statt rund 60 Dokumenten.
- Das Sprachmodell `german-gsd` steht unter der Lizenz CC BY-NC-SA. Es wird bei Bedarf heruntergeladen und nicht mit dem Projekt weitergegeben.
- Bei seltenen Personenbezeichnungen, deren männliche Form auf "-e" endet, bleibt ein verkürzter Stamm ("Weiterbildungspädagog"). Das betrifft einzelne Wörter, die ohnehin meist unter der Schwelle von 10 Dokumenten liegen und nicht ins Modell eingehen.

### Gespeicherte Dateien

| Datei | Inhalt |
|---|---|
| `data/interim/dokumente.rds` | 9.188 Dokumente mit Jahr, Kapitel, Seite, Überschrift und Text |
| `data/interim/udpipe_gsd.rds` | Ergebnis der Lemmatisierung |
| `data/interim/stm_daten.rds` | Eingabe für das Structural Topic Model |

### Nächster Schritt

Die Modellschätzung folgt in `02_stm_modell.ipynb`.